services:
  app:
    container_name: rsvp_manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - data:/app
      - uploads:/app/uploads
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  data:
  uploads: 