services:
  app:
    container_name: rsvp_manager
    image: ryderjj89/rsvp-manager:dev
    ports:
      - "3000:3000"
    volumes:
      - data:/app/database
      - uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - EMAIL_HOST=smtp.example.com
      - EMAIL_PORT=587
      - EMAIL_USER=your@email.com
      - EMAIL_PASS=yourpassword
      - EMAIL_FROM_NAME=RSVP Manager
      - EMAIL_FROM_ADDRESS=your@email.com
      - EMAIL_SECURE=false
      - FRONTEND_BASE_URL=https://your-frontend-domain.com
      - TZ=America/New_York # Set your desired timezone here
    restart: unless-stopped

volumes:
  data:
  uploads:
