services:
  app:
    container_name: rsvp_manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
    restart: unless-stopped

volumes:
  data:
  uploads: 